### ISSUE TITLE
Game stops progressing, no textboxes, no menu, just music

### ISSUE THREAD

**Issue by shugo589** [higurashi-mod/onikakushi#11]
In Chapter 7, specifically after this text box http://i.imgur.com/wmJXP0h.jpg and in chapter 12 at http://i.imgur.com/gEis6eE.jpg after this text box and once again in chapter 12 at this part: http://i.imgur.com/AZb2Pi4.jpg  the game stops progressing entirely. No new text boxes appear, the menu is inaccessible, just the background music keeps playing and alt f4 brings up the quit dialog.

The output log for the Chapter 7 stoppage is here: http://pastebin.com/A4pJ7Rk0 (I don't think all the loading stuff before is important, but if it is, I can give an entire output log)

The output log for the first Chapter 12 stoppage is http://pastebin.com/sLxP3s0f

The output log for the second Chapter 12 stoppage is http://pastebin.com/xPcakQgG

I don't know how the output log works but I don't think it needs all of those loading/unloading messages... correct me if I'm wrong and I'll paste it in its entirety.

I'm running the PS3 Voices and the Updated Steam Sprites, with the 1.1 patch. 

I got around it by uninstalling the mod and game entirely, reinstalling and playing a good deal past the stoppage, making a save, reapplying the patch, and loading the save.. It appears that saves in the patched game are further ahead than in the unpatched game, so I have to play a good bit ahead for a saved game in the unpatched version to progress past the broken text box.

Here is a saved file that loads the patched game almost immediately after the first stopped point in Chapter 12: http://a.pomf.se/mlxaoe.zip
Make sure you change the filename if you have a saved game in the 27th slot.

**Comment by ItaloKnox** [comment]
Just merged a whole new update, can you download the master file and try again? If it doesn't work, I'll try to do something about this.

**Comment by shugo589** [comment]
Assuming https://github.com/higurashi-mod/scripts/archive/master.zip is the master file, I'm not good at github, it still is not fixed.

**Comment by Cnnctr** [comment]
This is probably caused by missing files in the pack you have downloaded. Please, try to download the other one (Full PS3 mod 1.0) and check if it works with it. If it does, then you need to wait for TheGuraGuraMan to update the one you are using.

**Comment by shugo589** [comment]
Cool, the Full PS3 mod 1.0 gets me past these breaking points. Thanks a lot.

**Comment by enumag** [comment]
I've run into the same bug just now. I've looked into the log and into the script in question and I the problem is [here](https://github.com/higurashi-mod/onikakushi/blob/1ce35b0312048ff8f470609ddef4761c6dfb9639/Update/onik_010.txt#L252). You were right that the problem is a missing file. However it is in fact missing sprite for Chie-sensei which is a problem because the steam version doesn't have sprites for her at all. Not sure how to fix it.

**Comment by ItaloKnox** [comment]
Doesn't the graphics patch fix this? Since this patch is a voice + graphics patch, you are supposed to have both things. If that's not the case then we need to fix this.

**Comment by enumag** [comment]
It does not because it doesn't have her sprites either - it just uses steam alternate sprites + different backgrounds afaik.

The interesting fact though is that the game doesn't freeze on the first line where one of her sprites is used. The first time the sprite is just ignored and the game continues.

[Here](https://github.com/higurashi-mod/onikakushi/blob/1ce35b0312048ff8f470609ddef4761c6dfb9639/Update/onik_010.txt#L252) and [here](https://github.com/higurashi-mod/onikakushi/blob/1ce35b0312048ff8f470609ddef4761c6dfb9639/Update/onik_010.txt#L297) it works fine even if the sprite is missing. [This line](https://github.com/higurashi-mod/onikakushi/blob/1ce35b0312048ff8f470609ddef4761c6dfb9639/Update/onik_010.txt#L1539) is buggy. It seams that the problem is in which function is used to display the sprite - DrawBustshot ignores missing sprite while DrawBustshotWithFiltering freezes the game.

**Comment by ItaloKnox** [comment]
No, the sprite is definitely there. Aren't you running an older version of the graphics patch?
The 1.0 patch have everything needed to run the patch.

**Comment by enumag** [comment]
Not the full PS3 patch, the other one.

**Comment by shugo589** [comment]
Specifically the "Tweaked Steam sprites + ps3 assets 0.9" which has the PS3 backgrounds.

**Comment by enumag** [comment]
Yup. And I do have the up-to-date version. I'm very careful to not report something that was already fixed.

**Comment by ItaloKnox** [comment]
I think that patch is legacy now. Best you can do is to remove every instance of her sprite, or contact GuraGura and ask him to update the patch.

**Comment by enumag** [comment]
I like the steam sprites more than the PS3 sprites though  Guess I'll just merge both patches together or something.

**Comment by jezenielzapanta** [comment]
@enumag how did you resolve this? did you use the PS3 asset instead?

**Comment by ItaloKnox** [comment]
@jezenielzapanta If I recall correctly the PS3 assets are pretty much obligatory with the latest patch.

**Comment by enumag** [comment]
@jezenielzapanta New version of the patch should solve the problem.

**Comment by jezenielzapanta** [comment]
@enumag i am still experiencing the problem even though i used the master patch.. is this working with the tweaked steam graphics pack 1.5?

**Comment by ItaloKnox** [comment]
Talking about [this one](http://www.mediafire.com/download/5xncg6s51cc303r/Higurashi+Steam+-+Tweaked+Steam+sprites+%2B+PS3+assets+Mod+1.5+%5BWide+screen+support%5D.rar)? I'm using the exact same patch and my game is working fine. This bug is probably attached to something other than the patch/game.

**Comment by jezenielzapanta** [comment]
@ItaloKnox yes that is the graphics pack that i am using together with the `master.zip` patch version. Yes my game works, but on chapter 7 before Keiichi returns inside the room after conspiring with Rena the game does not proceed but the confirmation box  shows when pressing `alt-f4`.

What could be the alternate work around here? Should i empty the `CompiledScripts` directory?

**Comment by ItaloKnox** [comment]
@jezenielzapanta try that. Also upload your save file right before this bug happens, please.

**Comment by jezenielzapanta** [comment]
@ItaloKnox uhm, i tried emptying my `CompiledScripts` directory. I even started the chapter at the beginning to test.

This is my [save](http://s000.tinyupload.com/index.php?file_id=00301749770163983426) file.

**Comment by ItaloKnox** [comment]
@jezenielzapanta I'm not sure where is your problem, but I was able to play and skip through the whole chapter without a problem. Maybe you should consider reinstalling the game and the patches.

**Comment by jezenielzapanta** [comment]
@ItaloKnox still doesn't work, what OS, patch version and graphics version are you using? I made a full reinstall.. but it still doesn't work.. i'll just try deleting even my saves. Thanks for the quick response. I hope I can resolve this.. much better experience when using this mod.

**Comment by ItaloKnox** [comment]
@jezenielzapanta Windows 10, used Windows 8.1 when this thread started. Using the latest patch and the 1.5 widescreen graphics patch.

This is kinda odd, maybe you should ask Doddler for help in the Steam forums.

**Comment by jezenielzapanta** [comment]
@ItaloKnow I fixed it. I found the bug, there is a missing asset. The game is searching for the teacher's asset on `CG` so i copied the teacher's `CGAlt` to `CG`. Why is it searching inside `CG`?

**Comment by ItaloKnox** [comment]
@jezenielzapanta Can you tell me the filename of this asset? There's a chance the script is missing a line when the patch transition happened.

**Comment by jezenielzapanta** [comment]
@ItaloKnox `tie_def` it exists on `CGAlt` but not in `CG`. Is there no Chie Rumiko steam version sprite?

Full stack trace:
```
Could not find texture asset /home/shifter/.local/share/Steam/steamapps/common/Higurashi When They Cry/HigurashiEp01_Data/StreamingAssets/CG/tie_def.png
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/LinuxStandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

NullReferenceException: Object reference not set to an instance of an object
  at Assets.Scripts.Core.Scene.Layer.DrawLayerWithMask (System.String textureName, System.String maskName, Int32 x, Int32 y, Nullable`1 origin, Boolean isBustshot, Int32 style, Single wait, Boolean isBlocking) [0x00000] in <filename unknown>:0 
  at Assets.Scripts.Core.Scene.SceneController.DrawBustshotWithFiltering (Int32 layer, System.String textureName, System.String mask, Int32 x, Int32 y, Int32 z, Int32 originx, Int32 originy, Int32 oldx, Int32 oldy, Int32 oldz, Boolean move, Int32 priority, Int32 type, Single wait, Boolean isblocking) [0x00000] in <filename unknown>:0 
  at Assets.Scripts.Core.Buriko.BurikoScriptFile.OperationDrawBustshotWithFiltering () [0x00000] in <filename unknown>:0 
  at Assets.Scripts.Core.Buriko.BurikoScriptFile.ExecuteOperation (BurikoOperations op) [0x00000] in <filename unknown>:0 
  at Assets.Scripts.Core.Buriko.BurikoScriptFile.CommandOperation () [0x00000] in <filename unknown>:0 
  at Assets.Scripts.Core.Buriko.BurikoScriptFile.Next () [0x00000] in <filename unknown>:0 
  at Assets.Scripts.Core.Buriko.BurikoScriptSystem.Advance () [0x00000] in <filename unknown>:0 
  at Assets.Scripts.Core.GameSystem.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```

**Comment by ItaloKnox** [comment]
@jezenielzapanta Ohh, I see, I see. If I recall correctly, there is no Chie sprite in the original game. Are you playing with PS3 sprites **enabled**? My CG folder uses the old sprites, so if the game is running with these sprites enabled, the script will search for a Chie sprite when it doesn't exist.

I don't remember if that really happened, but I think some people never found this error because the patch was intended to use PS3 sprites on CGAlt and new PC sprites in CG.

**Comment by jezenielzapanta** [comment]
@ItaloKnox oh, I see.. so there is no Chie sprite for steam? I thought there was a Chie sprite because there is a Chie trading card in steam. Maybe we should document this case for future users.

**Comment by ItaloKnox** [comment]
@jezenielzapanta There is one, but it only appears if you use the updated sprites.
Since this patch was meant to have both updated and PS3 sprites instead of the old sprites, the script was changed to reflect these changes. So when you play with the old sprites, the game hangs because the script expected to find a Chie sprite there.

One last thing: can you screenshot the content of your CG and CGAlt folders? I need a screenshot with thumbnails visible, even better if they are showing sprites instead of backgrounds.

**Comment by enumag** [comment]
@ItaloKnox Are you sure? As far as I know mangagamer didn't include Chie sprite in the game (even though they made it as it can be seen on the card). The tweaked steam sprites patch uses Chie sprite from Higurashi Matsuri.

**Comment by jezenielzapanta** [comment]
@ItaloKnox sorry i reinstalled again to see if there is a chie sprite on the original. bad sadly there is no chie sprite... i will repatch again and send it if you still need it. Thanks by the way, maybe the README needs to be updated, maybe i can help.

@enumag yeah, sadly chie doesn't have any sprites..

**Comment by ItaloKnox** [comment]
@enumag My mistake, then. Regardless of that, the script files were altered to expect a Chie sprite in both folders.

@jezenielzapanta No need to take the screenshot, already found the answer I was looking for. I will change the readme right now.
